export const locationsList = [
    'Nicobar District, Andaman & Nicobar',
    'North & Middle Andaman, Andaman & Nicobar',
    'South Andaman, Andaman & Nicobar',
    'Port Blair, Andaman & Nicobar',

    'Araku, Andhara Pradesh',
    'Srikakulam, Andhara Pradesh',
    'Vizianagaram, Andhara Pradesh',
    'Visakhapatnam, Andhara Pradesh',
    'Anakapalli, Andhara Pradesh',
    'Kakinada, Andhara Pradesh',
    'Amalapuram, Andhara Pradesh',
    'Rajahmundry, Andhara Pradesh',
    'Narasapuram, Andhara Pradesh',
    'Eluru, Andhara Pradesh',
    'Machilipatnam, Andhara Pradesh',
    'Vijayawada, Andhara Pradesh',
    'Guntur, Andhara Pradesh',
    'Narasaraopet, Andhara Pradesh',
    'Bapatla, Andhara Pradesh',
    'Ongole, Andhara Pradesh',
    'Nandyal, Andhara Pradesh',
    'Kurnool, Andhara Pradesh',
    'Anantapur, Andhara Pradesh',
    'Hindupur, Andhara Pradesh',
    'Kadapa, Andhara Pradesh',
    'Nellore, Andhara Pradesh',
    'Tirupati, Andhara Pradesh',
    'Rajampet, Andhara Pradesh',
    'Chittoor, Andhara Pradesh',
    'Amaravati, Andhara Pradesh',

    'Tawang, Arunachal Pradesh',
    'West Kameng, Arunachal Pradesh',
    'East Kameng, Arunachal Pradesh',
    'Papum Pare, Arunachal Pradesh',
    'Upper Subansiri, Arunachal Pradesh',
    'Lower Subansiri, Arunachal Pradesh',
    'Kra-Daadi, Arunachal Pradesh',
    'Kurung Kumey, Arunachal Pradesh',
    'Siang, Arunachal Pradesh',
    'Upper Siang, Arunachal Pradesh',
    'Lower Siang, Arunachal Pradesh',
    'West Siang, Arunachal Pradesh',
    'East Siang, Arunachal Pradesh',
    'Dibang Valley, Arunachal Pradesh',
    'Lower Dibang Valley, Arunachal Pradesh',
    'Namsai, Arunachal Pradesh',
    'Changlang, Arunachal Pradesh',
    'Tirap, Arunachal Pradesh',
    'Longding, Arunachal Pradesh',
    'Lohit, Arunachal Pradesh',
    'Anjaw, Arunachal Pradesh',
    'Lepa Rada, Arunachal Pradesh',
    'Shi Yomi, Arunachal Pradesh',
    'Pakke-Kessang, Arunachal Pradesh',
    'Kamle, Arunachal Pradesh',
    'Itanagar, Arunachal Pradesh',

    'Karimaganj, Assam',
    'Hailakandi, Assam',
    'Cachar, Assam',
    'Karbi Anglong, Assam',
    'West Karbi Anglong, Assam',
    'South Salmara Mankachar, Assam',
    'Dhubri, Assam',
    'Kokrajhar, Assam',
    'Chirang, Assam',
    'Bongaigaon, Assam',
    'Goalpara, Assam',
    'Barpeta, Assam',
    'Bajali, Assam',
    'Kamrup, Assam',
    'Kamrup Metro, Assam',
    'Baksa, Assam',
    'Nalbari, Assam',
    'Udalguri, Assam',
    'Darrang, Assam',
    'Sonitpur, Assam',
    'Biswanath, Assam',
    'Marigaon, Assam',
    'Nagaon, Assam',
    'Hojai, Assam',
    'Golaghat, Assam',
    'Jorhat, Assam',
    'Sibsagar, Assam',
    'Charaideo, Assam',
    'Lakhimpur, Assam',
    'Dhemaji, Assam',
    'Dibrugarh, Assam',
    'Tinsukia, Assam',
    'Majuli, Assam',
    'Dima Hasao, Assam',
    'Guwahati, Assam',
    'Tezpur, Assam',
    'Silchar, Assam',

    'Valmiki Nagar, Bihar',
    'Paschim Champaran, Bihar',
    'Purvi Champaran, Bihar',
    'Sheohar, Bihar',
    'Sitamarhi, Bihar',
    'Madhubani, Bihar',
    'Jhanjharpur, Bihar',
    'Supaul, Bihar',
    'Araria, Bihar',
    'Kishanganj, Bihar',
    'Katihar, Bihar',
    'Purnia, Bihar',
    'Madhepura, Bihar',
    'Darbhanga, Bihar',
    'Muzaffarpur, Bihar',
    'Vaishali, Bihar',
    'Gopalganj, Bihar',
    'Siwan, Bihar',
    'Maharajganj, Bihar',
    'Saran, Bihar',
    'Hajipur, Bihar',
    'Ujiarpur, Bihar',
    'Samastipur, Bihar',
    'Begusarai, Bihar',
    'Khagaria, Bihar',
    'Bhagalpur, Bihar',
    'Banka, Bihar',
    'Munger, Bihar',
    'Nalanda, Bihar',
    'Patna Sahib, Bihar',
    'Pataliputra, Bihar',
    'Arrah, Bihar',
    'Buxar, Bihar',
    'Sasaram, Bihar',
    'Karakat, Bihar',
    'Jahanabad, Bihar',
    'Aurangabad, Bihar',
    'Gaya, Bihar',
    'Nawada, Bihar',
    'Jamui, Bihar',
    'Patna, Bihar',

    'Sarguja, Chhattisgarh',
    'Raigarh, Chhattisgarh',
    'Janjgir-Champa, Chhattisgarh',
    'Korba, Chhattisgarh',
    'Bilaspur, Chhattisgarh',
    'Rajnandgaon, Chhattisgarh',
    'Durg, Chhattisgarh',
    'Raipur, Chhattisgarh',
    'Mahasamund, Chhattisgarh',
    'Bastar, Chhattisgarh',
    'Kanker, Chhattisgarh',

    'Dadra and Nagar Haveli',
    'Daman and Diu',

    'Narela, Delhi',
    'Moti Nagar, Delhi',
    'Ambedkar Nagar, Delhi',
    'Burari, Delhi',
    'Sangam Vihar, Delhi',
    'Timarpur, Delhi',
    'Greater Kailash, Delhi',
    'Adarsh Nagar, Delhi',
    'Kalkaji, Delhi',
    'Badli, Delhi',
    'Tughlakabad, Delhi',
    'Rithala, Delhi',
    'Janakpuri, Delhi',
    'Badarpur, Delhi',
    'Bawana, Delhi',
    'Vikaspuri, Delhi',
    'Okhla, Delhi',
    'Mundka, Delhi',
    'Uttam Nagar, Delhi',
    'Trilokpuri, Delhi',
    'Kirari, Delhi',
    'Dwarka, Delhi',
    'Kondli, Delhi',
    'Sultan Pur Majra, Delhi',
    'Matiala, Delhi',
    'Patparganj, Delhi',
    'Nangloi Jat, Delhi',
    'Najafgarh, Delhi',
    'Laxmi Nagar, Delhi',
    'Mangol Puri, Delhi',
    'Bijwasan, Delhi',
    'Vishwas Nagar, Delhi',
    'Rohini, Delhi',
    'Palam, Delhi',
    'Krishna Nagar, Delhi',
    'Shalimar Bagh, Delhi',
    'Delhi Cantt, Delhi',
    'Gandhi Nagar, Delhi',
    'Shakur Basti, Delhi',
    'Rajinder Nagar, Delhi',
    'Shahdara, Delhi',
    'Tri Nagar, Delhi',
    'New Delhi, Delhi',
    'Seemapuri, Delhi',
    'Wazirpur, Delhi',
    'Jangpura, Delhi',
    'Rohtas Nagar, Delhi',
    'ModelTown, Delhi',
    'Kasturba Nagar, Delhi',
    'Seelam Pur, Delhi',
    'Sadar Bazar, Delhi',
    'Malviya Nagar, Delhi',
    'Ghonda, Delhi',
    'Chandni Chowk, Delhi',
    'R.K. Puram, Delhi',
    'Babarpur, Delhi',
    'Matia Mahal, Delhi',
    'Mehrauli, Delhi',
    'Gokalpur, Delhi',
    'Ballimaran, Delhi',
    'Chhatarpur, Delhi',
    'Mustafabad, Delhi',
    'Karol Bagh, Delhi',
    'Deoli, Delhi',
    'Karawal Nagar, Delhi',
    'Patel Nagar, Delhi',
    'Madipur, Delhi',
    'Rajouri Garden, Delhi',
    'Hari Nagar, Delhi',
    'Tilak Nagar, Delhi',
    'Nehru Place, Delhi',

    'North Goa, Goa',
    'South Goa, Goa',
    'Panaji, Goa',

    'Kachchh, Gujarat',
    'Banaskantha, Gujarat',
    'Patan, Gujarat',
    'Mahesana, Gujarat',
    'Sabarkantha, Gujarat',
    'Gandhinagar, Gujarat',
    'Ahmedabad East, Gujarat',
    'Ahmedabad West, Gujarat',
    'Surendranagar, Gujarat',
    'Rajkot, Gujarat',
    'Porbandar, Gujarat',
    'Jamnagar, Gujarat',
    'Junagadh, Gujarat',
    'Amreli, Gujarat',
    'Bhavnagar, Gujarat',
    'Anand, Gujarat',
    'Kheda, Gujarat',
    'Panchmahal, Gujarat',
    'Dahod, Gujarat',
    'Vadodara, Gujarat',
    'Chhota Udaipur, Gujarat',
    'Bharuch, Gujarat',
    'Bardoli, Gujarat',
    'Surat, Gujarat',
    'Navsari, Gujarat',
    'Valsad, Gujarat',
    'Ahmedabad, Gujarat',

    'Ambala, Haryana',
    'Kurukshetra, Haryana',
    'Sirsa, Haryana',
    'Hisar, Haryana',
    'Karnal, Haryana',
    'Sonipat, Haryana',
    'Rohtak, Haryana',
    'Bhiwani-Mahendragarh, Haryana',
    'Gurugram, Haryana',
    'Faridabad, Haryana',
    'Chandigarh, Haryana',

    'Kangra, Himachal Pradesh',
    'Mandi, Himachal Pradesh',
    'Hamirpur, Himachal Pradesh',
    'Dharamshala, Himachal Pradesh',
    'Shimla, Himachal Pradesh',

    'Baramulla, Jammu and Kashmir',
    'Anantnag–Rajouri, Jammu and Kashmir',
    'Udhampur, Jammu and Kashmir',
    'Jammu, Jammu and Kashmir',
    'Srinagar, Jammu and Kashmir',

    'Rajmahal, Jharkhand',
    'Dumka, Jharkhand',
    'Godda, Jharkhand',
    'Chatra, Jharkhand',
    'Kodarma, Jharkhand',
    'Giridih, Jharkhand',
    'Dhanbad, Jharkhand',
    'Jamshedpur, Jharkhand',
    'Singhbhum, Jharkhand',
    'Khunti, Jharkhand',
    'Lohardaga, Jharkhand',
    'Palamau, Jharkhand',
    'Hazaribagh, Jharkhand',
    'Ranchi, Jharkhand',

    'Chikkodi, Karnataka',
    'Belgaum, Karnataka',
    'Bagalkot, Karnataka',
    'Bijapur, Karnataka',
    'Gulbarga, Karnataka',
    'Raichur, Karnataka',
    'Bidar, Karnataka',
    'Koppal, Karnataka',
    'Bellary, Karnataka',
    'Haveri, Karnataka',
    'Dharwad, Karnataka',
    'Uttara Kannada, Karnataka',
    'Davanagere, Karnataka',
    'Shimoga, Karnataka',
    'Udupi Chikmagalur, Karnataka',
    'Hassan, Karnataka',
    'Dakshina Kannada, Karnataka',
    'Chitradurga, Karnataka',
    'Tumkur, Karnataka',
    'Mandya, Karnataka',
    'Mysore, Karnataka',
    'Chamarajanagar, Karnataka',
    'Bangalore Rural, Karnataka',
    'Bangalore North, Karnataka',
    'Bangalore Central, Karnataka',
    'Bangalore South, Karnataka',
    'Chikballapur, Karnataka',
    'Kolar, Karnataka',
    'Bengaluru, Karnataka',

    'Kasaragod, Kerala',
    'Kannur, Kerala',
    'Vatakara, Kerala',
    'Wayanad, Kerala',
    'Kozhikode, Kerala',
    'Malappuram, Kerala',
    'Ponnani, Kerala',
    'Palakkad, Kerala',
    'Alathur, Kerala',
    'Thrissur, Kerala',
    'Chalakudy, Kerala',
    'Ernakulam, Kerala',
    'Idukki, Kerala',
    'Kottayam, Kerala',
    'Alappuzha, Kerala',
    'Mavelikara, Kerala',
    'Pathanamthitta, Kerala',
    'Kollam, Kerala',
    'Attingal, Kerala',
    'Thiruvananthapuram, Kerala',

    'Ladakh, Ladakh',

    'Lakshadweep, Lakshadweep',

    'Morena, Madhya Pradesh',
    'Bhind, Madhya Pradesh',
    'Gwalior, Madhya Pradesh',
    'Guna, Madhya Pradesh',
    'Sagar, Madhya Pradesh',
    'Tikamgarh, Madhya Pradesh',
    'Damoh, Madhya Pradesh',
    'Khajuraho, Madhya Pradesh',
    'Satna, Madhya Pradesh',
    'Rewa, Madhya Pradesh',
    'Sidhi, Madhya Pradesh',
    'Shahdol, Madhya Pradesh',
    'Jabalpur, Madhya Pradesh',
    'Mandla, Madhya Pradesh',
    'Balaghat, Madhya Pradesh',
    'Chhindwara, Madhya Pradesh',
    'Hoshangabad, Madhya Pradesh',
    'Vidisha, Madhya Pradesh',
    'Rajgarh, Madhya Pradesh',
    'Dewas, Madhya Pradesh',
    'Ujjain, Madhya Pradesh',
    'Mandsour, Madhya Pradesh',
    'Ratlam, Madhya Pradesh',
    'Dhar, Madhya Pradesh',
    'Indore, Madhya Pradesh',
    'Khargone, Madhya Pradesh',
    'Khandwa, Madhya Pradesh',
    'Betul, Madhya Pradesh',
    'Bhopal, Madhya Pradesh',

    'Nandurbar, Maharashtra',
    'Dhule, Maharashtra',
    'Jalgaon, Maharashtra',
    'Raver, Maharashtra',
    'Buldhana, Maharashtra',
    'Akola, Maharashtra',
    'Amravati, Maharashtra',
    'Wardha, Maharashtra',
    'Ramtek, Maharashtra',
    'Nagpur, Maharashtra',
    'Bhandara–Gondiya, Maharashtra',
    'Gadchiroli–Chimur, Maharashtra',
    'Chandrapur, Maharashtra',
    'Yavatmal–Washim, Maharashtra',
    'Hingoli, Maharashtra',
    'Nanded, Maharashtra',
    'Parbhani, Maharashtra',
    'Jalna, Maharashtra',
    'Aurangabad, Maharashtra',
    'Dindori, Maharashtra',
    'Nashik, Maharashtra',
    'Palghar, Maharashtra',
    'Bhiwandi, Maharashtra',
    'Kalyan, Maharashtra',
    'Thane, Maharashtra',
    'Mumbai North, Maharashtra',
    'Mumbai North West, Maharashtra',
    'Mumbai North East, Maharashtra',
    'Mumbai North Central, Maharashtra',
    'Mumbai South Central, Maharashtra',
    'Mumbai South, Maharashtra',
    'Raigad, Maharashtra',
    'Maval, Maharashtra',
    'Pune, Maharashtra',
    'Baramati, Maharashtra',
    'Shirur, Maharashtra',
    'Ahmednagar, Maharashtra',
    'Shirdi, Maharashtra',
    'Beed, Maharashtra',
    'Osmanabad, Maharashtra',
    'Latur, Maharashtra',
    'Solapur, Maharashtra',
    'Madha, Maharashtra',
    'Sangli, Maharashtra',
    'Satara, Maharashtra',
    'Ratnagiri–Sindhudurg, Maharashtra',
    'Kolhapur, Maharashtra',
    'Hatkanangle, Maharashtra',
    'Mumbai, Maharashtra',

    'Inner Manipur, Manipur',
    'Outer Manipur, Manipur',
    'Imphal, Manipur',

    'Tura, Meghalaya',
    'Shillong, Meghalaya',

    'Aizawl, Mizoram',

    'Kohima, Nagaland',

    'Bargarh, Odisha',
    'Sundargarh, Odisha',
    'Sambalpur, Odisha',
    'Keonjhar, Odisha',
    'Mayurbhanj, Odisha',
    'Balasore, Odisha',
    'Bhadrak, Odisha',
    'Jajpur, Odisha',
    'Dhenkanal, Odisha',
    'Bolangir, Odisha',
    'Kalahandi, Odisha',
    'Nabarangpur, Odisha',
    'Kandhamal, Odisha',
    'Cuttack, Odisha',
    'Kendrapara, Odisha',
    'Jagatsinghpur, Odisha',
    'Puri, Odisha',
    'Aska, Odisha',
    'Berhampur, Odisha',
    'Koraput, Odisha',
    'Bhubaneswar, Odisha',

    'Puducherry, Puducherry',

    'Gurdaspur, Punjab',
    'Khadoor Sahib, Punjab',
    'Jalandhar, Punjab',
    'Hoshiarpur, Punjab',
    'Anandpur Sahib, Punjab',
    'Ludhiana, Punjab',
    'Fatehgarh Sahib, Punjab',
    'Faridkot, Punjab',
    'Firozpur, Punjab',
    'Bathinda, Punjab',
    'Sangrur, Punjab',
    'Patiala, Punjab',
    'Amritsar, Punjab',

    'Ganganagar, Rajasthan',
    'Bikaner, Rajasthan',
    'Churu, Rajasthan',
    'Jhunjhunu, Rajasthan',
    'Sikar, Rajasthan',
    'Jaipur Rural, Rajasthan',
    'Alwar, Rajasthan',
    'Bharatpur, Rajasthan',
    'Karauli–Dholpur, Rajasthan',
    'Dausa, Rajasthan',
    'Tonk–Sawai Madhopur, Rajasthan',
    'Ajmer, Rajasthan',
    'Nagaur, Rajasthan',
    'Pali, Rajasthan',
    'Jodhpur, Rajasthan',
    'Barmer, Rajasthan',
    'Jalore, Rajasthan',
    'Udaipur, Rajasthan',
    'Banswara, Rajasthan',
    'Chittorgarh, Rajasthan',
    'Rajsamand, Rajasthan',
    'Bhilwara, Rajasthan',
    'Kota, Rajasthan',
    'Jhalawar–Baran, Rajasthan',
    'Jaipur, Rajasthan',

    'Gangtok, Sikkim',

    'Thiruvallur, Tamil Nadu',
    'Chennai North, Tamil Nadu',
    'Chennai South, Tamil Nadu',
    'Chennai Central, Tamil Nadu',
    'Sriperumbudur, Tamil Nadu',
    'Kancheepuram, Tamil Nadu',
    'Arakkonam, Tamil Nadu',
    'Vellore, Tamil Nadu',
    'Krishnagiri, Tamil Nadu',
    'Dharmapuri, Tamil Nadu',
    'Tiruvannamalai, Tamil Nadu',
    'Arani, Tamil Nadu',
    'Villupuram, Tamil Nadu',
    'Kallakurichi, Tamil Nadu',
    'Salem, Tamil Nadu',
    'Namakkal, Tamil Nadu',
    'Erode, Tamil Nadu',
    'Tiruppur, Tamil Nadu',
    'Nilgiris, Tamil Nadu',
    'Coimbatore, Tamil Nadu',
    'Pollachi, Tamil Nadu',
    'Dindigul, Tamil Nadu',
    'Karur, Tamil Nadu',
    'Tiruchirappalli, Tamil Nadu',
    'Perambalur, Tamil Nadu',
    'Cuddalore, Tamil Nadu',
    'Chidambaram, Tamil Nadu',
    'Mayiladuturai, Tamil Nadu',
    'Nagapattinam, Tamil Nadu',
    'Thanjavur, Tamil Nadu',
    'Sivaganga, Tamil Nadu',
    'Madurai, Tamil Nadu',
    'Theni, Tamil Nadu',
    'Virudhunagar, Tamil Nadu',
    'Ramanathapuram, Tamil Nadu',
    'Thoothukkudi, Tamil Nadu',
    'Tenkasi, Tamil Nadu',
    'Tirunelveli, Tamil Nadu',
    'Kanyakumari, Tamil Nadu',
    'Chennai, Tamil Nadu',

    'Adilabad, Telangana',
    'Peddapalle, Telangana',
    'Karimnagar, Telangana',
    'Nizamabad, Telangana',
    'Zahirabad, Telangana',
    'Medak, Telangana',
    'Malkajgiri, Telangana',
    'Secunderabad, Telangana',
    'Chevella, Telangana',
    'Mahbubnagar, Telangana',
    'Nagarkurnool, Telangana',
    'Nalgonda, Telangana',
    'Bhongir, Telangana',
    'Warangal, Telangana',
    'Mahabubabad, Telangana',
    'Khammam, Telangana',
    'Hyderabad, Telangana',

    'Tripura West, Tripura',
    'Tripura East, Tripura',
    'Agartala, Tripura',

    'Saharanpur, Uttar Pradesh',
    'Kairana, Uttar Pradesh',
    'Muzaffarnagar, Uttar Pradesh',
    'Bijnor, Uttar Pradesh',
    'Nagina, Uttar Pradesh',
    'Moradabad, Uttar Pradesh',
    'Rampur, Uttar Pradesh',
    'Sambhal, Uttar Pradesh',
    'Amroha, Uttar Pradesh',
    'Meerut, Uttar Pradesh',
    'Baghpat, Uttar Pradesh',
    'Ghaziabad, Uttar Pradesh',
    'Gautam Buddha Nagar, Uttar Pradesh',
    'Bulandshahr, Uttar Pradesh',
    'Aligarh, Uttar Pradesh',
    'Hathras, Uttar Pradesh',
    'Mathura, Uttar Pradesh',
    'Agra, Uttar Pradesh',
    'Fatehpur Sikri, Uttar Pradesh',
    'Firozabad, Uttar Pradesh',
    'Mainpuri, Uttar Pradesh',
    'Etah, Uttar Pradesh',
    'Badaun, Uttar Pradesh',
    'Aonla, Uttar Pradesh',
    'Bareilly, Uttar Pradesh',
    'Pilibhit, Uttar Pradesh',
    'Shahjahanpur, Uttar Pradesh',
    'Kheri, Uttar Pradesh',
    'Dhaurahra, Uttar Pradesh',
    'Sitapur, Uttar Pradesh',
    'Hardoi, Uttar Pradesh',
    'Misrikh, Uttar Pradesh',
    'Unnao, Uttar Pradesh',
    'Mohanlalganj, Uttar Pradesh',
    'Rae Bareli, Uttar Pradesh',
    'Amethi, Uttar Pradesh',
    'Sultanpur, Uttar Pradesh',
    'Pratapgarh, Uttar Pradesh',
    'Farrukhabad, Uttar Pradesh',
    'Etawah, Uttar Pradesh',
    'Kannauj, Uttar Pradesh',
    'Kanpur Urban, Uttar Pradesh',
    'Akbarpur, Uttar Pradesh',
    'Jalaun, Uttar Pradesh',
    'Jhansi, Uttar Pradesh',
    'Hamirpur, Uttar Pradesh',
    'Banda, Uttar Pradesh',
    'Fatehpur, Uttar Pradesh',
    'Kaushambi, Uttar Pradesh',
    'Phulpur, Uttar Pradesh',
    'Allahabad, Uttar Pradesh',
    'Barabanki, Uttar Pradesh',
    'Faizabad, Uttar Pradesh',
    'Ambedkar Nagar, Uttar Pradesh',
    'Bahraich, Uttar Pradesh',
    'Kaiserganj, Uttar Pradesh',
    'Shrawasti, Uttar Pradesh',
    'Gonda, Uttar Pradesh',
    'Domariyaganj, Uttar Pradesh',
    'Basti, Uttar Pradesh',
    'Sant Kabir Nagar, Uttar Pradesh',
    'Maharajganj, Uttar Pradesh',
    'Gorakhpur, Uttar Pradesh',
    'Kushi Nagar, Uttar Pradesh',
    'Deoria, Uttar Pradesh',
    'Bansgaon, Uttar Pradesh',
    'Lalganj, Uttar Pradesh',
    'Azamgarh, Uttar Pradesh',
    'Ghosi, Uttar Pradesh',
    'Salempur, Uttar Pradesh',
    'Ballia, Uttar Pradesh',
    'Jaunpur, Uttar Pradesh',
    'Machhlishahr, Uttar Pradesh',
    'Ghazipur, Uttar Pradesh',
    'Chandauli, Uttar Pradesh',
    'Varanasi, Uttar Pradesh',
    'Bhadohi, Uttar Pradesh',
    'Mirzapur, Uttar Pradesh',
    'Robertsganj, Uttar Pradesh',
    'Noida, Uttar Pradesh',
    'Greater Noida, Uttar Pradesh',
    'Lucknow, Uttar Pradesh',

    'Tehri Garhwal, Uttarakhand',
    'Garhwal, Uttarakhand',
    'Almora, Uttarakhand',
    'Nainital–Udhamsingh Nagar, Uttarakhand',
    'Haridwar, Uttarakhand',
    'Dehradun, Uttarakhand',

    'Cooch Behar, West Bengal',
    'Alipurduars, West Bengal',
    'Jalpaiguri, West Bengal',
    'Darjeeling, West Bengal',
    'Raiganj, West Bengal',
    'Balurghat, West Bengal',
    'Maldaha Uttar, West Bengal',
    'Maldaha Dakshin, West Bengal',
    'Jangipur, West Bengal',
    'Baharampur, West Bengal',
    'Murshidabad, West Bengal',
    'Krishnanagar, West Bengal',
    'Ranaghat, West Bengal',
    'Bangaon, West Bengal',
    'Barrackpore, West Bengal',
    'Dum Dum, West Bengal',
    'Barasat, West Bengal',
    'Basirhat, West Bengal',
    'Jaynagar, West Bengal',
    'Mathurapur, West Bengal',
    'Diamond Harbour, West Bengal',
    'Jadavpur, West Bengal',
    'Kolkata Dakshin, West Bengal',
    'Kolkata Uttar, West Bengal',
    'Howrah, West Bengal',
    'Uluberia, West Bengal',
    'Srerampur, West Bengal',
    'Hooghly, West Bengal',
    'Arambag, West Bengal',
    'Tamluk, West Bengal',
    'Kanthi, West Bengal',
    'Ghatal, West Bengal',
    'Jhargram, West Bengal',
    'Medinipur, West Bengal',
    'Purulia, West Bengal',
    'Bankura, West Bengal',
    'Bishnupur, West Bengal',
    'Bardhaman Purba, West Bengal',
    'Bardhaman–Durgapur, West Bengal',
    'Asansol, West Bengal',
    'Bolpur, West Bengal',
    'Birbhum, West Bengal',
    'Siliguri, West Bengal',
    'New Jalpaiguri, West Bengal',
    'Kolkata, West Bengal',
]